# NIFH DIAZATROPS DATA SET
This notebook aims to explore and analyze the data from the 2 datasets with focus on the nifh gene data sheet in .xls file.

In [39]:
#we import all they key libraries needed in this notebook
import numpy as np
import pandas as pd
import xarray as xr
import matplotlib.pyplot as plt

There are some simple functions we would like to use for both datasets that I also used in another notebook(obs_diazotr.ipynb). And since they are useful and can and should be used here i copied over the code.

In [40]:
#this function removes all not specified columns from the dataframe
def removeRed(keepers, df):
    cols = set(df.columns) - set(keepers)
    df.drop(columns=list(cols), inplace=True)

#this function converts object columns to numeric
def objToNum(df):
    object_columns = df.select_dtypes(include='object').columns.tolist()
    for col in object_columns:
        df[col]=pd.to_numeric(df[col], errors="coerce")

In [41]:
keepers = ['LATITUDE', 'LONGITUDE', 'DEPTH (m)','Trichodesmium nifH Gene (x106 copies m-3)', 'UCYN-A1 nifH Gene (x106 copies m-3)','UCYN-B nifH Gene (x106 copies m-3)',"UCYN-A nifH Gene (x106 copies m-3)","Heterocyst (Richelia & Calotrhix) Biomass (mg C m-3)", 'Gamma A nifH Gene (x106 copies/m3)',]

# First dataset
This dataset is from the paper [Global oceanic diazotroph database version 2 and
elevated estimate of global oceanic N2 fixation](https://essd.copernicus.org/articles/15/3673/2023/essd-15-3673-2023-assets.html).

In [42]:
dzdb_2024_nifh = pd.read_csv("./csv/DiazotrophsDatabase-20240109_nifh.csv")
print(dzdb_2024_nifh.shape)
print(dzdb_2024_nifh.columns)
dzdb_2024_nifh.head()

(5580, 25)
Index(['SOURCE: Related article or authors',
       'METHODS:                  Sampling/Analysis', 'DATE (yyyy-mm-dd)',
       'LATITUDE', 'LONGITUDE', 'DEPTH (m)',
       'Trichodesmium nifH Gene (x106 copies m-3)',
       'UCYN-A1 nifH Gene (x106 copies m-3)',
       'UCYN-A2/A3/A4 nifH Gene (x106 copies m-3)',
       'Total UCYN-A nifH Gene (x106 copies m-3)',
       'UCYN-B nifH Gene (x106 copies m-3)',
       'UCYN-C nifH Gene (x106 copies m-3)', 'Richelia Associated Species',
       'Total Richelia (het-1 +het-2) nifH Gene (x106 copies m-3)',
       'Richelia  (het-1 or RintRC02) nifH Gene (x106 copies m-3)',
       'Richelia  (het-2 or ReuHH01) nifH Gene (x106 copies m-3)',
       'Richelia  ( RrhiSC01) nifH Gene (x106 copies m-3)', 'Temperature (˚C)',
       'Salinity (PSU)', 'Nitrate (µM)', 'Phosphate (µM)', 'Fe (nM)',
       'SiO2 (µM)', 'Chlorophyll  (mg m-3)', 'Notes'],
      dtype='object')

,SOURCE: Related article or authors,METHODS: Sampling/Analysis,DATE (yyyy-mm-dd),LATITUDE,LONGITUDE,DEPTH (m),Trichodesmium nifH Gene (x106 copies m-3),UCYN-A1 nifH Gene (x106 copies m-3),UCYN-A2/A3/A4 nifH Gene (x106 copies m-3),Total UCYN-A nifH Gene (x106 copies m-3),...,Richelia (het-2 or ReuHH01) nifH Gene (x106 copies m-3),Richelia ( RrhiSC01) nifH Gene (x106 copies m-3),Temperature (˚C),Salinity (PSU),Nitrate (µM),Phosphate (µM),Fe (nM),SiO2 (µM),Chlorophyll (mg m-3),Notes
0,"Bonnet et al. (2008), doi:10.5194/bg-5-215-2008",qPCR,10/31/2004,-9.00,-136.86,5.0,0.000,0.03,NaN,0.03,...,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,qPCR,11/3/2004,-11.51,-134.35,5.0,0.000,0.00,NaN,0.00,...,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,qPCR,11/4/2004,-13.31,-132.39,70.0,0.000,0.00,NaN,0.00,...,NaN,0.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,qPCR,11/5/2004,-15.20,-130.20,5.0,0.000,0.00,NaN,0.00,...,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,qPCR,11/6/2004,-16.87,-128.38,5.0,0.000,0.00,NaN,0.00,...,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
dzdb_2024_nifh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5580 entries, 0 to 5579
Data columns (total 25 columns):
 #   Column                                                     Non-Null Count  Dtype
---  ------                                                     --------------  -----
 0   SOURCE: Related article or authors                         143 non-null    object
 1   METHODS:                  Sampling/Analysis                5580 non-null   object
 2   DATE (yyyy-mm-dd)                                          5580 non-null   object
 3   LATITUDE                                                   5580 non-null   float64
 4   LONGITUDE                                                  5580 non-null   float64
 5   DEPTH (m)                                                  5580 non-null   float64
 6   Trichodesmium nifH Gene (x106 copies m-3)                  4192 non-null   object
 7   UCYN-A1 nifH Gene (x106 copies m-3)                        4387 non-null   object
 8   UCYN-A2/A3/A4 nifH Gene (x106 copies m-3)                  1134 non-null   object
 9   Total UCYN-A nifH Gene (x106 copies m-3)                   4444 non-null   object
 10  UCYN-B nifH Gene (x106 copies m-3)                         3832 non-null   object
 11  UCYN-C nifH Gene (x106 copies m-3)                         1118 non-null   object
 12  Richelia Associated Species                                2985 non-null   object
 13  Total Richelia (het-1 +het-2) nifH Gene (x106 copies m-3)  3104 non-null   object
 14  Richelia  (het-1 or RintRC02) nifH Gene (x106 copies m-3)  425 non-null    object
 15  Richelia  (het-2 or ReuHH01) nifH Gene (x106 copies m-3)   603 non-null    object
 16  Richelia  ( RrhiSC01) nifH Gene (x106 copies m-3)          1436 non-null   object
 17  Temperature (˚C)                                           1513 non-null   object
 18  Salinity (PSU)                                             1408 non-null   object
 19  Nitrate (µM)                                               1184 non-null   object
 20  Phosphate (µM)                                             1266 non-null   object
 21  Fe (nM)                                                    44 non-null     float64
 22  SiO2 (µM)                                                  272 non-null    object
 23  Chlorophyll  (mg m-3)                                      540 non-null    float64
 24  Notes                                                      376 non-null    object
dtypes: float64(5), object(20)
memory usage: 1.1+ MB

In [44]:
removeRed(keepers, dzdb_2024_nifh)
objToNum(dzdb_2024_nifh)
dzdb_2024_nifh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5580 entries, 0 to 5579
Data columns (total 6 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   LATITUDE                                   5580 non-null   float64
 1   LONGITUDE                                  5580 non-null   float64
 2   DEPTH (m)                                  5580 non-null   float64
 3   Trichodesmium nifH Gene (x106 copies m-3)  3352 non-null   float64
 4   UCYN-A1 nifH Gene (x106 copies m-3)        3468 non-null   float64
 5   UCYN-B nifH Gene (x106 copies m-3)         3199 non-null   float64
dtypes: float64(6)
memory usage: 261.7 KB

# Second dataset
This is the dataset from the  [Database of diazotrophs in global ocean: abundance, biomass and nitrogen fixation rates](https://doi.pangaea.de/10.1594/PANGAEA.774851)

In [45]:
#here we open the dataset of the other database for cell count
maredat_nifh = pd.read_csv("./csv/MAREDAT_diazotroph_nifh.csv")
print(maredat_nifh.shape)
print(maredat_nifh.columns)
maredat_nifh.head()

(921, 35)
Index(['SOURCE: Data', 'SOURCE: Related article',
       'METHODS:                  Sampling/Analysis', 'DATE (yyyy-mm-dd)',
       'LATITUDE', 'LONGITUDE', 'DEPTH (m)',
       'Trichodesmium nifH Gene (x106 copies m-3)',
       'Trichodesmium Biomass Conversion factor (mg C/106 nifH copies)',
       'Trichodesmium Biomass (mg C m-3)',
       'UCYN-A nifH Gene (x106 copies m-3)',
       'UCYN-A Biomass Conversion factor (mg C/106 nifH copies)',
       'UCYN-B nifH Gene (x106 copies m-3)',
       'UCYN-B Biomass Conversion factor (mg C/106 nifH copies)',
       'UCYN-C nifH Gene (x106 copies m-3)',
       'UCYN-C Biomass Conversion factor (mg C/106 nifH copies)',
       'UCYN Biomass (mg C m-3)', 'Richelia Associated Species',
       'Richelia nifH Gene (x106 copies m-3)',
       'Richelia Biomass Conversion factor (mg C/106 nifH copies)',
       'Calothrix Associated Species',
       'Calothrix nifH Gene  (x106 copies m-3)',
       'Calothrix Biomass Conversion factor (mg C/106 nifH copies)',
       'Heterocyst (Richelia & Calotrhix) Biomass (mg C m-3)',
       'Total Diazotrophic Biomass (mg C m-3)', 'Temperature (˚C)',
       'Salinity (PSU)', 'Nitrate (µM)', 'Phosphate (µM)', 'Fe (nM)',
       'Chlorophyll  (mg m-3)', 'Notes', 'Gamma A nifH Gene (x106 copies/m3)',
       'Gamma P nifH Gene (x106 copies/m3)',
       'CIII nifH Gene (x106 copies/m3)'],
      dtype='object')

,SOURCE: Data,SOURCE: Related article,METHODS: Sampling/Analysis,DATE (yyyy-mm-dd),LATITUDE,LONGITUDE,DEPTH (m),Trichodesmium nifH Gene (x106 copies m-3),Trichodesmium Biomass Conversion factor (mg C/106 nifH copies),Trichodesmium Biomass (mg C m-3),...,Temperature (˚C),Salinity (PSU),Nitrate (µM),Phosphate (µM),Fe (nM),Chlorophyll (mg m-3),Notes,Gamma A nifH Gene (x106 copies/m3),Gamma P nifH Gene (x106 copies/m3),CIII nifH Gene (x106 copies/m3)
0,"Bonnet, S., Aix Marseille Université, sophie.b...","Bonnet et al. (2008), doi:10.5194/bg-5-215-2008",qPCR,2004-10-31,-9.00,-136.86,5,0.0,0.3,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Bonnet, S., Aix Marseille Université, sophie.b...","Bonnet et al. (2008), doi:10.5194/bg-5-215-2008",qPCR,2004-11-03,-11.51,-134.35,5,0.0,0.3,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Bonnet, S., Aix Marseille Université, sophie.b...","Bonnet et al. (2008), doi:10.5194/bg-5-215-2008",qPCR,2004-11-04,-13.31,-132.39,70,0.0,0.3,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Bonnet, S., Aix Marseille Université, sophie.b...","Bonnet et al. (2008), doi:10.5194/bg-5-215-2008",qPCR,2004-11-05,-15.20,-130.20,5,0.0,0.3,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Bonnet, S., Aix Marseille Université, sophie.b...","Bonnet et al. (2008), doi:10.5194/bg-5-215-2008",qPCR,2004-11-06,-16.87,-128.38,5,0.0,0.3,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
maredat_nifh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 921 entries, 0 to 920
Data columns (total 35 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   SOURCE: Data                                                    825 non-null    object
 1   SOURCE: Related article                                         878 non-null    object
 2   METHODS:                  Sampling/Analysis                     921 non-null    object
 3   DATE (yyyy-mm-dd)                                               921 non-null    object
 4   LATITUDE                                                        921 non-null    float64
 5   LONGITUDE                                                       921 non-null    float64
 6   DEPTH (m)                                                       921 non-null    int64
 7   Trichodesmium nifH Gene (x106 copies m-3)                       759 non-null    float64
 8   Trichodesmium Biomass Conversion factor (mg C/106 nifH copies)  760 non-null    float64
 9   Trichodesmium Biomass (mg C m-3)                                759 non-null    float64
 10  UCYN-A nifH Gene (x106 copies m-3)                              771 non-null    float64
 11  UCYN-A Biomass Conversion factor (mg C/106 nifH copies)         771 non-null    float64
 12  UCYN-B nifH Gene (x106 copies m-3)                              795 non-null    float64
 13  UCYN-B Biomass Conversion factor (mg C/106 nifH copies)         795 non-null    float64
 14  UCYN-C nifH Gene (x106 copies m-3)                              226 non-null    float64
 15  UCYN-C Biomass Conversion factor (mg C/106 nifH copies)         226 non-null    float64
 16  UCYN Biomass (mg C m-3)                                         840 non-null    float64
 17  Richelia Associated Species                                     509 non-null    object
 18  Richelia nifH Gene (x106 copies m-3)                            535 non-null    float64
 19  Richelia Biomass Conversion factor (mg C/106 nifH copies)       535 non-null    float64
 20  Calothrix Associated Species                                    44 non-null     object
 21  Calothrix nifH Gene  (x106 copies m-3)                          64 non-null     float64
 22  Calothrix Biomass Conversion factor (mg C/106 nifH copies)      64 non-null     float64
 23  Heterocyst (Richelia & Calotrhix) Biomass (mg C m-3)            555 non-null    float64
 24  Total Diazotrophic Biomass (mg C m-3)                           907 non-null    float64
 25  Temperature (˚C)                                                647 non-null    float64
 26  Salinity (PSU)                                                  708 non-null    float64
 27  Nitrate (µM)                                                    362 non-null    float64
 28  Phosphate (µM)                                                  444 non-null    float64
 29  Fe (nM)                                                         13 non-null     float64
 30  Chlorophyll  (mg m-3)                                           208 non-null    float64
 31  Notes                                                           329 non-null    object
 32  Gamma A nifH Gene (x106 copies/m3)                              151 non-null    float64
 33  Gamma P nifH Gene (x106 copies/m3)                              140 non-null    float64
 34  CIII nifH Gene (x106 copies/m3)                                 148 non-null    float64
dtypes: float64(27), int64(1), object(7)
memory usage: 252.0+ KB

In [47]:
removeRed(keepers, maredat_nifh)
objToNum(maredat_nifh)
maredat_nifh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 921 entries, 0 to 920
Data columns (total 8 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   LATITUDE                                              921 non-null    float64
 1   LONGITUDE                                             921 non-null    float64
 2   DEPTH (m)                                             921 non-null    int64
 3   Trichodesmium nifH Gene (x106 copies m-3)             759 non-null    float64
 4   UCYN-A nifH Gene (x106 copies m-3)                    771 non-null    float64
 5   UCYN-B nifH Gene (x106 copies m-3)                    795 non-null    float64
 6   Heterocyst (Richelia & Calotrhix) Biomass (mg C m-3)  555 non-null    float64
 7   Gamma A nifH Gene (x106 copies/m3)                    151 non-null    float64
dtypes: float64(7), int64(1)
memory usage: 57.7 KB